### ISSUE TITLE
1.5 update: renamed/moved items

### ISSUE THREAD

**Issue by dawnmist** [emipa606/PawnRules#2]
I've been poking at the Pawn Rules mod, and it appears that a couple of the items being patched have been moved/renamed in Rimworld 1.5 (Anomaly).

These are:
- `Rimworld.FoodRestriction.Allows` => `Rimworld.FoodPolicy.Allows`
- `Rimworld.Pawn_FoodRestrictionTracker.CurrentFoodRestriction` => `Rimworld.Pawn_FoodRestrictionTracker.CurrentFoodPolicy` (returns type `FoodPolicy`).

I don't know how to check if the language keys like `Lang.Get("FoodRestrictionsOverridden")` have been similarly renamed, and the version of msbuild that I have access to on my linux machine doesn't like namespace statements that do not wrap the content of the file so I can't compile the mod for 1.5 locally to test it further.

It looks like the `FoodRestriction` object also got renamed to `FoodPolicy`, so some of the other functions may now need updating their parameters/return values to match.

I am hoping that this information helps you when it comes time to update the mod. ❤️

**Comment by emipa606** [comment]
Thank you for the info!
The mod should be updated in 
ad9320d
Hope it helps!
